package frontrouter

import (
	"crypto/tls"
	"errors"
	"net"
	"testing"
	"time"
)

// clientHello captures the first flight a real TLS client writes.
//
// Generated by crypto/tls rather than assembled by hand: a hand-built fixture
// tests the parser against the author's idea of a ClientHello, and the bytes
// this parser has to survive are whatever the client library actually emits —
// including the extensions and padding a fixture would never think to include.
func clientHello(t *testing.T, serverName string) []byte {
	t.Helper()
	client, server := net.Pipe()
	got := make(chan []byte, 1)
	go func() {
		buf := make([]byte, 8192)
		n, _ := server.Read(buf)
		got <- append([]byte(nil), buf[:n]...)
		_ = server.Close()
	}()
	// The handshake cannot complete — nothing answers — but the first flight is
	// written before it fails, and that is the whole input to this parser.
	_ = tls.Client(client, &tls.Config{
		ServerName:         serverName,
		InsecureSkipVerify: true,
	}).Handshake()
	_ = client.Close()
	select {
	case b := <-got:
		return b
	case <-time.After(5 * time.Second):
		t.Fatal("timed out capturing the ClientHello")
		return nil
	}
}

func TestServerNameReadsARealClientHello(t *testing.T) {
	got, err := ServerName(clientHello(t, "DoT.Example.COM"))
	if err != nil {
		t.Fatalf("ServerName: %v", err)
	}
	// Lower-cased for the same reason QuestionName lower-cases: SNI is
	// case-insensitive on the wire and the routing table is keyed lower.
	if got != "dot.example.com" {
		t.Fatalf("server name = %q, want dot.example.com", got)
	}
}

func TestServerNameRejectsWhatItCannotRoute(t *testing.T) {
	// A ClientHello with no SNI at all. Routing it would mean guessing, and a
	// guess here sends an encrypted stream to a backend holding the wrong
	// certificate — which the client rejects with an error naming neither the
	// router nor the real cause.
	noSNI := clientHello(t, "")

	// A DNS query arriving on the TLS port. Cheap to confuse with a record
	// header if the parser only checks length.
	dnsPacket := buildQuery("tunnel.example.com")

	for _, tc := range []struct {
		name   string
		packet []byte
		want   error
	}{
		{"no SNI extension", noSNI, ErrNoServerName},
		{"not TLS at all", dnsPacket, ErrNotClientHello},
		{"empty", nil, ErrNotClientHello},
		{"record header only", []byte{0x16, 0x03, 0x01, 0x00, 0x05}, ErrShortClientHello},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ServerName(tc.packet)
			if !errors.Is(err, tc.want) {
				t.Fatalf("err = %v, want %v", err, tc.want)
			}
		})
	}
}

// A ClientHello larger than one TCP segment is normal — post-quantum key shares
// alone push it past 1500 bytes — so the reader must keep pulling until the
// record is whole. Truncating it and giving up would break exactly the modern
// clients this is meant to carry.
func TestServerNameNeedsTheWholeRecord(t *testing.T) {
	full := clientHello(t, "split.example.com")
	if len(full) < 64 {
		t.Fatalf("captured hello is implausibly short (%d bytes)", len(full))
	}
	if _, err := ServerName(full[:len(full)-8]); !errors.Is(err, ErrShortClientHello) {
		t.Fatalf("a truncated hello must report ErrShortClientHello, got %v", err)
	}
	if _, err := ServerName(full); err != nil {
		t.Fatalf("the whole record must parse: %v", err)
	}
}
